name: Deploy to Firebase Hosting
permissions:
  contents: read
  id-token: write
  pull-requests: read
on:
  push:
    branches:
      - main
      - MAROON-staging
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch/environment to deploy"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - MAROON-staging

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main'
    defaults:
      run:
        working-directory: bee-prec-app
    environment:
      name: production
      url: https://bee-prec-site.web.app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies and build Flutter web
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter build web --release

      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANNY_TECH }}'
          channelId: live
          projectId: nanny-tech
          target: bee-prec-site

  deploy-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'push' && github.ref == 'refs/heads/MAROON-staging' || github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'MAROON-staging'
    defaults:
      run:
        working-directory: bee-prec-app
    environment:
      name: staging
      url: https://bee-prec-site-staging.web.app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies and build Flutter web
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter build web --release

      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANNY_TECH }}'
          channelId: live
          projectId: nanny-tech
          target: bee-prec-site-staging
