name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - MAROON-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANNY_TECH }}'
          channelId: live
          projectId: nanny-tech
          target: bee-prec-site
      - name: Deploy staging
        if: github.ref == 'refs/heads/MAROON-staging'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANNY_TECH }}'
          channelId: live
          projectId: nanny-tech
          target: bee-prec-site-staging
