name: ZAP Baseline Scan
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL'
        required: false
        default: 'https://bee-prec-site.web.app'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP baseline
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target || 'https://bee-prec-site.web.app' }}
          rules_file_name: ignore.rules
          cmd_options: '-a'
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-baseline-report.html
